document.write("<table width="+"100%"+"  border="+"0"+" cellspacing="+"0"+" cellpadding="+"0"+">");
  document.write("<tr>");
	document.write("<td width="+"27%"+" align="+"left"+" valign="+"top"+"><a href="+"http://www.spec-india.com/index.htm"+"><img src="+"images/logo.gif"+" width="+"210"+" height="+"59"+" border="+"0"+" alt="+"SPEC&nbsp;India&nbsp;(A&nbsp;Systems&nbsp;Plus&nbsp;Initiative)"+"></a></td>");
    document.write("<td width="+"43%"+">&nbsp;</td>");
    document.write("<td width="+"30%"+"><table width="+"100%"+"  border="+"0"+" cellspacing="+"0"+" cellpadding="+"0"+">");
        document.write("<tr>");
          document.write("<td><table width="+"100%"+"  border="+"0"+" cellspacing="+"0"+" cellpadding="+"0"+">");
              document.write("<tr>");
                document.write("<td width="+"25%"+" align="+"right"+"><a href="+"http://www.spec-india.com/index.htm"+"><img src="+"images/home_icon.gif"+" width="+"17"+" height="+"16"+" border="+"0"+" alt="+"SPEC&nbsp;India&nbsp;Home"+"></a></td>");
                document.write("<td width="+"5%"+" align="+"center"+" valign="+"middle"+"><span class="+"div"+">|</span></td>");
				document.write("<td width="+"10%"+" align="+"right"+"><a href="+"javascript:window.print()"+"><img src="+"images/icon_home.jpg"+" width="+"19"+" height="+"21"+" border="+"0"+" alt="+"Print"+"></a></td>");
				document.write("<td width="+"5%"+" align="+"center"+" valign="+"middle"+"><span class="+"div"+">|</span></td>");
                document.write("<td width="+"12%"+" align="+"center"+"><a href="+"http://www.spec-india.com/sitemap.htm"+"><img src="+"images/icon_sitemap.jpg"+" width="+"13"+" height="+"14"+" border="+"0"+" alt="+"Sitemap"+"></a></td>");
                document.write("<td width="+"4%"+" align="+"center"+" valign="+"middle"+"><span class="+"div"+">|</span></td>");
                document.write("<td width="+"10%"+" align="+"center"+" valign="+"middle"+"><a href="+"http://www.spec-india.com/contactus.php"+"><img src="+"images/icon_mail.jpg"+" width="+"17"+" height="+"15"+" border="+"0"+" alt="+"Contact&nbsp;Us"+"></a></td>");
				document.write("<td width="+"5%"+" align="+"center"+" valign="+"middle"+"><span class="+"div"+">|</span></td>");
				document.write("<td width="+"18%"+" align="+"center"+" valign="+"middle"+"><a href="+"http://blog.spec-india.com/"+" span class="+"blog"+" style="+"text-decoration:none;"+">Blog</a></td>");
              document.write("</tr>");
            document.write("</table></td>");
		document.write("</tr>");
        document.write("<tr><td>&nbsp;</td></tr>");
      document.write("</table></td>");
    document.write("</tr>");
  document.write("</table>");